# Generated by Django 5.1.3 on 2024-11-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_first_name_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refillrequest',
            name='quantity',
        ),
    ]
