# Generated by Django 5.1.3 on 2024-11-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_refillrequest_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
